// BACKEND NOTE
// WHAT IS BACKEND?
// THIS REFERS TO THE PART OF A WEBSITE THAT OPERATES ON THE SERVER SIDE, BEHIND THE SCENES.
// RESPONSIBLE FOR MANAGING AND PROCESSING the data, handling business logic and performing tasks the FRONTEND CANNOT HANDLE.
// WHAT DO WE USE BACKEND TO DO?
// 1. SERVER: THE BACKEND RUNS ON THE SERVER, WHICH CAN BE A SINGLE COMPUTER/LAPTOP, A CLUSTER OF  COMPUTERS OR SUPER COMPUTERS WHICH HOUSES THE WEBSITE/WEBAPPS
// 2. DATABASE: THE BACKEND INTERACTS WITH A DATABASE TO STORE AND RETRIEVE DATA. THIS INCLUDES USER INFORMATION, CONTENTS AND OTHER DATA NECESSARY FOR THE WEBSITE FUNCTIONALITY. (MONGODB)
//3. SERVERSIDE PROGRAMMING LANGUAGES: JAVERSCRIPT/TYPESCRIPT(NODE/{FRAMEWORK: EXPRESS}), PYTHON(DJANGO), PHP(LARAVEL)
// 4. API: (APPLICATION PROGRAMMING INTERFACE) THE BACKEND CAN EXPOSE THE APIS THAT THE FRONTEND USES TO REQUEST AND SEND DATA.
// 5.AUTHENTICATION AND AUTHORIZATION:THE BACKEND MANAGES USERS AUTHENTICATION (VERIFYING IDENTITY) AND AUTHORIZATION (GRANTING ACCESS TO RESOURCES BASED ON PERMISSION)
// 6.SECURITY: THE BACKEND IMPLIMENTS SECURITY MEASURES TO PROTECT DATA AND ENSURES THAT THE APPLICATION IS SAFE FROM VULNERABILITIES

// TOOLS USED FOR BACKEND DEVELOPMENT
// 1.VS CODE (CODE EDITOR)
// DATABASE: POSTGRES, MYSQL, MONGODB, NOSQL
// LANGUAGES: NODE...EXPRESS
// TESTERS: POSTMAN

// REQUEST AND RESPONSIBLE
// REQUEST: 5 TYPES OF REQUEST
// 1. POST REQUEST: USER SENDING THEIR INFORMATION TO A SERVER/DATABASE E.G LOGING, SIGN-UP, INPUTS ETC
// 2.GET REQUEST: RETRIEVES DATA FROM THE SERVER/DATABASE
// DELETE REQUEST: LOG-OUT, DELETE ACCOUNT, DELETE A POST.
// 4.PATCH REQUEST:TO EDIT A DATA THAT HAS ALREADY BEEN POSTED.
// 5. PUT REQUEST: TO UPDATE A DATA THAT HAS ALREADY BEEN POSTED
//  RESPONSE
// GOOD RESPONSE
// STATUS CODE

// Bacckend Flow
//STEEP 1: APP.TS, INDEX.TS, MAIN.TS, THIS IS WHERE YOU RUN YOUR SERVER AND CONNECT TO YOUR DATABASE
// STEP 2, YOU CREATE A MODEL FOLDER: THIS IS FOR DEFINING THE STRUCTURE OF THE DATA THAT WILL BE STORED IN YOUR DATABASE
// STEP 3. YOU CREATE THE CONTROLLER FOLDER: THIS IS WHERE THE  BUSINESS LOGIC HAPPENS...WHERE YOU DEFINE WHAT HAPPENS BETWEEN REQUEST AND RESPONS.
// STEP 4:YOU CREATE THE ROUTE FOLDER: THIS IS WHERE YOU DEFINE YOUR REQUEST ROUTE
// STEP 5: YOU BRING EVERYTHING BACK YOUR SERVER FILE
// STEP 6: OTHER FOLDERS YOU MIGHT CREATE DEPENDING ON THE SCALE OF THE PROJECT: 1. UTILS FOLDER (UTILITIES), MIDDLEWARE FOLDER ETC.

//for cosnt use :
//npm i --save-dev@types/node

//for import use :
//npm i --save-dev@types/express
